# This script removes the blankets in between rtt lines in the orignal delay data file generated by tshark.
import sys
import datetime
starttime = datetime.datetime.now()
print starttime
import struct
import math
import datetime
import os
def count_lines_textfile(filepath):
	cnt = -1
	for cnt, line in enumerate(open(filepath, 'r')):
		pass

	return cnt + 1


proto=sys.argv[1]
date=sys.argv[2]

infilename=proto+'_'+date+'_delay_4000.txt'
outfilename=proto+'_'+date+'_delay_4000_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm

infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_4001.txt'
outfilename=proto+'_'+date+'_delay_4001_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_6000.txt'
outfilename=proto+'_'+date+'_delay_6000_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_6001.txt'
outfilename=proto+'_'+date+'_delay_6001_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_6002.txt'
outfilename=proto+'_'+date+'_delay_6002_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_8000.txt'
outfilename=proto+'_'+date+'_delay_8000_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_8001.txt'
outfilename=proto+'_'+date+'_delay_8001_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_8002.txt'
outfilename=proto+'_'+date+'_delay_8002_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_8003.txt'
outfilename=proto+'_'+date+'_delay_8003_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num



i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


infilename=proto+'_'+date+'_delay_8004.txt'
outfilename=proto+'_'+date+'_delay_8004_compacted.txt'
infile=open(infilename,'r')
outfile=open(outfilename,'w')
num=count_lines_textfile(infilename)

print 'Count lines:',num


i=0
sm=0
while i<num:
	line=infile.readline()
	if line=='\n':
		i+=1
	else:
		outfile.write(line)
		sm+=float(line)
		i+=1

sm/=i
print 'avg:',sm


infile.close()
outfile.close()


endtime=datetime.datetime.now()
print 'took',(endtime-starttime).seconds,'seconds'
